version: "3"
services:
  1panel:
    # image: moelin/1panel:latest
    image: shao/1panel:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # - PANELVER=v1.6.1
        - EX_PORT=8080
    container_name: 1panel # 容器名
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/OrbStack/docker/volumes:/var/lib/docker/volumes
      - ~/Work/1panel:/Users/shao/Work/1panel
    environment:
      - TZ=Asia/Shanghai # 时区设置
    ports:
      - 8080:8080

networks:
  default:
    name: 1panel-network
    external: true
